steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/n8n-aiassi-evo-image/evolution-api:latest', '.']
# Push the container image to Artifact Registry
images:
- 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/n8n-aiassi-evo-image/evolution-api:latest'
